
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JInternalFrame;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 50687
 */

public class formulario extends JInternalFrame {
    int prom; 
     private Estudiante student;    
     
  
     
  
    public formulario() {
        initComponents();
        nombre.setInputVerifier(new InputVerifier() {
    @Override
    public boolean verify(JComponent input) {
        String texto = ((JTextField) input).getText();
        // Verificar si el texto contiene solo letras (incluyendo letras con acentos) y tiene más de 3 caracteres
        return texto.matches("[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ]+") && texto.length() > 3;
    }
});
        apellido1.setInputVerifier(new InputVerifier() {
    @Override
    public boolean verify(JComponent input) {
        String texto = ((JTextField) input).getText();
        // Verificar si el texto contiene solo letras (incluyendo letras con acentos) y tiene más de 3 caracteres
        return texto.matches("[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ]+") && texto.length() > 3;
    }
});
        apellido2.setInputVerifier(new InputVerifier() {
    @Override
    public boolean verify(JComponent input) {
        String texto = ((JTextField) input).getText();
        // Verificar si el texto contiene solo letras (incluyendo letras con acentos) y tiene más de 3 caracteres
        return texto.matches("[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ]+") && texto.length() > 3;
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    

                   

    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JTextField();
        apellido1 = new javax.swing.JTextField();
        apellido2 = new javax.swing.JTextField();
        carrera = new javax.swing.JComboBox<>();
        aceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        proyecto1 = new javax.swing.JSpinner();
        proyecto2 = new javax.swing.JSpinner();
        encuesta = new javax.swing.JSpinner();
        juego = new javax.swing.JSpinner();
        foro = new javax.swing.JSpinner();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        carrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medicina", "Ingeniería Civil", "Psicología", "Administración de Empresas", "Derecho", "Economía", "Enfermería", "Arquitectura", "Educación", "Ingeniería Informática", "Contabilidad", "Comunicación", "Marketing", "Biología", "Ciencias de la Computación" }));

        aceptar.setText("Enviar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido 2");

        jLabel3.setText("Apellido 1 ");

        jLabel4.setText("Carrera");

        jLabel5.setText("Proyecto 1");

        jLabel6.setText("Proyecto 2");

        jLabel7.setText("Foro Académico");

        jLabel8.setText("Encuesta");

        jLabel9.setText("Juego");

        proyecto1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        proyecto2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        encuesta.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        juego.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        foro.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aceptar)
                        .addGap(18, 18, 18)
                        .addComponent(Salir)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(apellido1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(apellido2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nombre, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 499, Short.MAX_VALUE)
                                .addComponent(encuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 459, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(proyecto1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(proyecto2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(foro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(juego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(proyecto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(proyecto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(foro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(encuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(juego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(Salir))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
         
     try {
        // Crear una nueva instancia de Estudiante
        this.student = new Estudiante();

        // Establecer los atributos del estudiante
        this.student.setNombre(this.nombre.getText());
        this.student.setApellido1(this.apellido1.getText());
        this.student.setApellido2(this.apellido2.getText());
        String carreraSeleccionada = (String) carrera.getSelectedItem();/** Es lógico que existen más carreras, 
         * pero se ha cerrado con fines de validación a las indicadas en el combo box */
        this.student.setCarrera(carreraSeleccionada);

        // Obtener los valores de los JSpinner
        /**Nota**: A pesar de haberse seteado los spinners tanto en este como en el Formulario2
         para trabajar con números del 0-100, el sistema acepta ingresar más de 100 y menos de 0. 
         Igualmente se considera una opción útil en caso de necesidad de edición*/
        int notaProyecto1 = (int) proyecto1.getValue();
        int notaProyecto2 = (int) proyecto2.getValue();
        int notaForo = (int) foro.getValue();
        int notaJuego = (int) juego.getValue();
        int notaEncuesta = (int) encuesta.getValue();

        // Establecer las notas en el estudiante
        this.student.setProyecto1(notaProyecto1);
        this.student.setProyecto2(notaProyecto2);
        this.student.setForo(notaForo);
        this.student.setJuego(notaJuego);
        this.student.setEncuesta(notaEncuesta);

        // Mostrar el mensaje de registro
        JOptionPane.showMessageDialog(null, "Estudiante registrado");
         Promedios promedio = new Promedios();
     prom = promedio.calcularPromedio(notaProyecto1, notaProyecto2, notaForo, notaJuego, notaEncuesta);

        
        // Guardar el estudiante en el archivo
  

    } catch(Exception ex) {
        JOptionPane.showMessageDialog(null, "Error al registrar estudiante: " + ex.getMessage());
    } 
    
     guardarEstudiante();
     guardarPromedio();

   
    }//GEN-LAST:event_aceptarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
         this.dispose(); // Cierra la ventana interna actual
    }//GEN-LAST:event_SalirActionPerformed
private void guardarEstudiante() {
        try (BufferedWriter lapicero = new BufferedWriter(new FileWriter("Estudiantes.txt", true))) {
            // Escribir los datos del estudiante en el archivo
            lapicero.write(student.getId() + "," + student.getNombre() + "," + student.getApellido1() + ","
                    + student.getApellido2() + "," + student.getCarrera() + "," + student.getProyecto1() + ","
                    + student.getProyecto2() + "," + student.getForo() + "," + student.getEncuesta() + ","
                    + student.getJuego());
            lapicero.newLine();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }


public void guardarPromedio() {
        try (BufferedWriter lapicero = new BufferedWriter(new FileWriter("Promedios.txt", true))) {
            // Escribir los datos del estudiante en el archivo
            lapicero.write(student.getId() + "," + student.getNombre() + "," + student.getApellido1() + ","
                    + student.getApellido2() + "," + student.getCarrera() + "," + prom);
            lapicero.newLine();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField apellido1;
    private javax.swing.JTextField apellido2;
    private javax.swing.JComboBox<String> carrera;
    private javax.swing.JSpinner encuesta;
    private javax.swing.JSpinner foro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner juego;
    private javax.swing.JTextField nombre;
    private javax.swing.JSpinner proyecto1;
    private javax.swing.JSpinner proyecto2;
    // End of variables declaration//GEN-END:variables
}
